### ISSUE TITLE
How to solves this problem?

### ISSUE THREAD

**Issue by mbpz** [TonnyL/Espresso#4]
All packages are not available for download!  The following packages are not available:
- Package id extras;android;m2repository

**Comment by TonnyL** [comment]
May I have a look at the code of your `build.gradle`(app level) file?

**Comment by mbpz** [comment]
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/io.github.marktony.espresso-1.apk"],nativeLibraryDirectories=[/data/app-lib/io.github.marktony.espresso-1, /vendor/lib, /system/lib]]

**Comment by mbpz** [comment]
com.android.tools.build:gradle:2.3.0

**Comment by TonnyL** [comment]
It may be caused by the configuration of your manifest.xml file or the configuration of instant run.See the questions below on StackOverFlow, maybe you can find solutions:
+ [Didn't find class “com.google.firebase.provider.FirebaseInitProvider”?](http://stackoverflow.com/questions/39825543/didnt-find-class-com-google-firebase-provider-firebaseinitprovider)
+ [Unable to get provider com.google.firebase.provider.FirebaseInitProvider](http://stackoverflow.com/questions/37312103/unable-to-get-provider-com-google-firebase-provider-firebaseinitprovider)

**Comment by mbpz** [comment]
thx

**Comment by TonnyL** [comment]
If you have any problem about this project, do not hesitate and open another issue, let's find the way to solve them. Good luck!
